//path: src\modules\Agents\Internal\components\sampleAgents.tsx

import { Agent } from "@modules/Agents/types";

export const sampleAgents: Agent[] = [
    {
        imgUrl: "/images/bird80px.png",
        name: "Brainwave",
        role: "Moderator",
        status: "active",
        dateModified: "20/10/23",
        dateCreated: "01/01/23",
    },
    {
        imgUrl: "/images/bird80px.png",
        name: "Aine",
        role: "Administrator",
        status: "inactive",
        dateModified: "15/10/23",
        dateCreated: "02/01/23",
    },
    {
        imgUrl: "/images/bird80px.png",
        name: "Searchbot",
        role: "User",
        status: "active",
        dateModified: "10/10/23",
        dateCreated: "03/01/23",
    },
    {
        imgUrl: "/images/bird80px.png",
        name: "Pointer bot",
        role: "User",
        status: "active",
        dateModified: "09/10/23",
        dateCreated: "04/01/23",
    },
    {
        imgUrl: "/images/bird80px.png",
        name: "Claude",
        role: "Moderator",
        status: "active",
        dateModified: "08/10/23",
        dateCreated: "05/01/23",
    },
    {
        imgUrl: "/images/bird80px.png",
        name: "Pi",
        role: "User",
        status: "inactive",
        dateModified: "07/10/23",
        dateCreated: "06/01/23",
    },
    {
        imgUrl: "/images/bird80px.png",
        name: "Robotnik",
        role: "User",
        status: "active",
        dateModified: "06/10/23",
        dateCreated: "07/01/23",
    },
    {
        imgUrl: "/images/bird80px.png",
        name: "Louise",
        role: "Administrator",
        status: "active",
        dateModified: "05/10/23",
        dateCreated: "08/01/23",
    },
    {
        imgUrl: "/images/bird80px.png",
        name: "Helptron",
        role: "Moderator",
        status: "inactive",
        dateModified: "04/10/23",
        dateCreated: "09/01/23",
    },
    {
        imgUrl: "/images/bird80px.png",
        name: "Bender",
        role: "User",
        status: "inactive",
        dateModified: "03/10/23",
        dateCreated: "10/01/23",
    },
];
