name: CI

on:
          push:
                    branches: [main]
          pull_request:
                    branches: [main]

jobs:
          build:
                    runs-on: ubuntu-latest

                    steps:
                              - uses: actions/checkout@v2
                              - name: Use Node.js 16
                                uses: actions/setup-node@v2
                                with:
                                          node-version: 16

                              - name: Install dependencies
                                run: pnpm install

                              - name: Run Jest Tests
                                run: pnpm run test:generate-output

                              - name: Publish Unit Test Results
                                uses: EnricoMi/publish-unit-test-result-action@v1
                                if: always()
                                with:
                                          files: .jest-test-results.json
